npm i @babel/core -D &&
npm i @babel/plugin-proposal-class-properties -D &&
npm i @babel/plugin-syntax-dynamic-import -D &&
npm i @babel/polyfill -D &&
npm i @babel/preset-env -D &&
npm i @babel/preset-react -D &&
npm i @types/axios -D &&
npm i @types/history -D &&
npm i @types/moment -D &&
npm i @types/react -D &&
npm i @types/react-dom -D &&
npm i @types/react-router-dom -D &&
npm i @types/yup -D &&
npm i @typescript-eslint/eslint-plugin -D &&
npm i @typescript-eslint/parser -D &&
npm i babel-eslint -D &&
npm i babel-loader -D &&
npm i bootstrap -D &&
npm i clean-webpack-plugin -D &&
npm i compression-webpack-plugin -D &&
npm i concurrently -D &&
npm i css-loader -D &&
npm i dotenv-webpack -D &&
npm i eslint -D &&
npm i eslint-config-react-app -D &&
npm i eslint-loader -D &&
npm i eslint-plugin-flowtype -D &&
npm i eslint-plugin-import -D &&
npm i eslint-plugin-jsx-a11y -D &&
npm i eslint-plugin-react -D &&
npm i eslint-plugin-react-hooks -D &&
npm i file-loader -D &&
npm i html-webpack-change-assets-extension-plugin -D &&
npm i html-webpack-plugin -D &&
npm i ignore-loader -D &&
npm i node-sass -D &&
npm i nodemon -D &&
npm i nodemon-webpack-plugin -D &&
npm i prettier -D &&
npm i sass-loader -D &&
npm i source-map-loader -D &&
npm i style-loader -D &&
npm i ts-loader -D &&
npm i typescript -D &&
npm i webpack -D &&
npm i webpack-bundle-analyzer -D &&
npm i webpack-cli -D &&
npm i webpack-node-externals -D